name: Selenium Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
          
      - name: Set Up Chrome and ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chrome-version: 'stable'
          
      - name: Verify Chrome and ChromeDriver Versions
        run: |
          google-chrome --version || echo "Google Chrome not found"
          chromedriver --version || echo "ChromeDriver not found"
          
      - name: Run Tests with Maven
        run: mvn test
        
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}
          path: target/surefire-reports/
