name: Selenium Test Automation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    # Manual trigger option

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      test_groups: ${{ steps.set-matrix.outputs.test_groups }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Define test groups
        id: set-matrix
        run: |
          # Define test groups for parallel execution
          echo "test_groups=[\"ui-tests\", \"api-tests\"]" >> $GITHUB_OUTPUT

  test:
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Continue running other jobs even if one fails
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        test_group: ${{ fromJson(needs.setup.outputs.test_groups) }}
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    # Ubuntu Chrome setup
    - name: Setup Chrome on Ubuntu
      if: runner.os == 'Linux'
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
    
    # Windows Chrome setup
    - name: Setup Chrome on Windows
      if: runner.os == 'Windows'
      run: |
        choco install googlechrome
        choco install chromedriver
    
    # macOS Chrome setup
    - name: Setup Chrome on macOS
      if: runner.os == 'macOS'
      run: |
        brew install --cask google-chrome
        brew install --cask chromedriver
        
    - name: Install dependencies
      run: |
        mvn clean install -DskipTests
      shell: bash
        
    - name: Run Selenium tests - UI Tests
      if: matrix.test_group == 'ui-tests'
      run: |
        mvn test -Dgroups=ui-tests
      shell: bash
      
    - name: Run Selenium tests - API Tests
      if: matrix.test_group == 'api-tests'
      run: |
        mvn test -Dgroups=api-tests
      shell: bash
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.test_group }}
        path: target/surefire-reports/
