name: Selenium Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set Up Chrome and ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chrome-version: 'stable'


      - name: Run Tests with Maven
        run: mvn test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}
          path: target/surefire-reports/
          
      - name: Check Test Status
        id: check_status
        if: always()
        run: |
          if [ "${{ steps.test.outcome }}" == "success" ]; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "emoji=✅" >> $GITHUB_OUTPUT
            echo "message=Tests passed successfully!" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "emoji=❌" >> $GITHUB_OUTPUT
            echo "message=Tests failed! Check logs for details." >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Send Slack Notification
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ steps.check_status.outputs.status }}
          fields: repo,message,commit,author,action,workflow,job
          text: |
            ${{ steps.check_status.outputs.emoji }} ${{ steps.check_status.outputs.message }}
            Repository: ${{ github.repository }}
            OS: ${{ maxtrix.os }}
            Workflow: ${{ github.workflow }}
            Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          # YOU NEED TO ADD THIS SECRET: Create a Slack webhook URL and add it to your GitHub repository secrets
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          # To create a Slack webhook:
          # 1. Go to your Slack workspace > Administration > Manage apps
          # 2. Search for "Incoming Webhooks" and add to workspace
          # 3. Create a new webhook for a specific channel
          # 4. Copy the webhook URL
          # 5. Add it as a repository secret in GitHub: Settings > Secrets > New repository secret

  notification:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check Test Matrix Status
        id: status_check
        run: |
          if [ "${{ needs.test.result }}" == "success" ]; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "subject=✅ Selenium Tests Passed" >> $GITHUB_OUTPUT
            echo "body=All Selenium tests passed successfully across all operating systems." >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "subject=❌ Selenium Tests Failed" >> $GITHUB_OUTPUT
            echo "body=One or more Selenium tests failed. Please check the GitHub Actions logs for more details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}     
          server_port: ${{ secrets.MAIL_PORT }}         
          username: ${{ secrets.MAIL_USERNAME }}          
          password: ${{ secrets.MAIL_PASSWORD }}          
          subject: ${{ steps.status_check.outputs.subject }} - ${{ github.repository }}
          body: |
            ${{ steps.status_check.outputs.body }}
            
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref_name }}
            Triggered by: ${{ github.actor }}
            
            View detailed logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          from: CI Pipeline <${{ secrets.MAIL_USERNAME }}>
          to: ${{ secrets.NOTIFICATION_EMAIL }} 
          secure: true
          
